name: Zonaprop Bot (hourly)

on:
  workflow_dispatch:    # para ejecutarlo manualmente
  schedule:
    - cron: "0 * * * *" # cada hora a los 00 minutos (UTC)

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: "1"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # Restaura el historial de avisos (seen.json) si existe
      - name: Restore seen.json cache
        uses: actions/cache/restore@v4
        with:
          path: .data/seen.json
          key: seen
          restore-keys: |
            seen

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
        run: |
          python main.py

      # Guarda el seen.json actualizado para próximas corridas
      - name: Save seen.json cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .data/seen.json
          key: seen-${{ github.run_id }}
