name: Telegram test
on: workflow_dispatch

jobs:
  send-test:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje de prueba a Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          echo "Ping a Telegram..."
          RESP=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
                 -d chat_id="${CHAT_ID}" \
                 -d text="✅ Test desde GitHub Actions")
          echo "Respuesta: $RESP"
          echo "$RESP" | grep -q '"ok":true' && echo "OK enviado" || (echo "FALLÓ"; exit 1)
